services:
  - type: web
    name: jan-ai-chatbot
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: FB_PAGE_ACCESS_TOKEN
        sync: false
      - key: FB_VERIFY_TOKEN
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_UID
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: USE_FALLBACK_AI
        sync: false
