name: Jan-Bot-24-7

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show directory content
        run: ls -la

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jan Bot
        env:
          SIMULATED_INPUT: "হানি, আজকে একটু রোমান্টিক হও 🥰"
          SIMULATED_UID: "100015569688497"
        run: |
          python main.py
