name: Jan-Bot (24/7)

on: push: branches: - main schedule: - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs: run-bot: runs-on: ubuntu-latest

env:
  CI: "true"
  SIMULATED_INPUT: "হানি, আজকে একটু রোমান্টিক হও 🥰"
  SIMULATED_UID: "100015569688497"

steps:
  - name: Checkout code
    uses: actions/checkout@v3

  - name: Show directory content
    run: ls -la

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.11'

  - name: Install dependencies
    run: |
      pip install -r requirements.txt
      pip install python-dotenv

  - name: Run Jan Bot (with CI test if enabled)
    run: |
      echo "🤖 Running Jan Bot..."
      if [ "$CI" = "true" ]; then
        echo "📥 Simulated input mode: $SIMULATED_INPUT from $SIMULATED_UID"
        python -c "import os; from main import process_message; process_message({'sender_id': os.environ['SIMULATED_UID'], 'text': os.environ['SIMULATED_INPUT']})"
      else
        python main.py

